// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendSys.Data;

#nullable disable

namespace VendSys.Migrations
{
    [DbContext(typeof(VdiDexDbContext))]
    [Migration("20250327013014_AddDEXMeterAndLaneMeter")]
    partial class AddDEXMeterAndLaneMeter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VendSys.Models.DEXLaneMeter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DEXMeterId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfVends")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValueOfPaidSalves")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DEXMeterId");

                    b.ToTable("DEXLaneMeters");
                });

            modelBuilder.Entity("VendSys.Models.DEXMeter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DEXDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValueOfPaidVends")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DEXMeters");
                });

            modelBuilder.Entity("VendSys.Models.DEXLaneMeter", b =>
                {
                    b.HasOne("VendSys.Models.DEXMeter", "DEXMeter")
                        .WithMany("LaneMeters")
                        .HasForeignKey("DEXMeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DEXMeter");
                });

            modelBuilder.Entity("VendSys.Models.DEXMeter", b =>
                {
                    b.Navigation("LaneMeters");
                });
#pragma warning restore 612, 618
        }
    }
}
